### ISSUE TITLE
Error after using knife tool

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1591]
Do the following for reproducing the situation:
1. Draw a shape
2. switch to knife tool
3. do a cut
4. switch back to shape tool
5. draw shape

Error:
```
Uncaught (in promise) RemoteError: TypeError("'NoneType' object does not support item assignment")
    at RemoteObject._handleIncomingMessage (remote.3dabd224.js:109:32)
    at websocket.onmessage (remote.3dabd224.js:65:48)
_handleIncomingMessage @ remote.3dabd224.js:109
websocket.onmessage @ remote.3dabd224.js:65
await in websocket.onmessage
_editGlyphOrInstanceUnchecked @ scene-controller.3dabd224.js:1064
await in _editGlyphOrInstanceUnchecked
_editGlyphOrInstance @ scene-controller.3dabd224.js:969
_editGlyphOrInstanceAndRecordChanges @ scene-controller.3dabd224.js:923
editGlyphAndRecordChanges @ scene-controller.3dabd224.js:859
addShapePath @ edit-tools-shape.3dabd224.js:84
handleDrag @ edit-tools-shape.3dabd224.js:80
await in handleDrag
handleDrag @ scene-controller.3dabd224.js:714
drag @ scene-controller.3dabd224.js:377
handleMouseDown @ mouse-tracker.3dabd224.js:60
(anonymous) @ mouse-tracker.3dabd224.js:16

```

https://github.com/user-attachments/assets/bfa3d40d-b232-43b5-b8e1-a31b47f575fe

**Comment by justvanrossum** [comment]
Ouch, can reproduce.
