### ISSUE TITLE
Align Objects does not work anymore

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1663]
There is a bug with the feature 'Align Objects':

```
panel-transformation.9379f9d2.js:931 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'xMax')
    at panel-transformation.9379f9d2.js:931:57
    at Array.map (<anonymous>)
    at Object.computeDeltasFromBoundingBoxes (panel-transformation.9379f9d2.js:931:34)
    at panel-transformation.9379f9d2.js:830:39
    at SceneController._editGlyphOrInstanceUnchecked (scene-controller.9379f9d2.js:1077:22)
    at async SceneController._editGlyphOrInstance (scene-controller.9379f9d2.js:1004:14)
    at async SceneController.editGlyph (scene-controller.9379f9d2.js:979:12)
    at async TransformationPanel.moveObjects (panel-transformation.9379f9d2.js:816:5)
```

and also with 'Distribute Objects':
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'xMin')
    at rectCenter (rectangle.9379f9d2.js:112:21)
    at DistributeObjectsDescriptor.compareObjects (panel-transformation.9379f9d2.js:1029:7)
    at panel-transformation.9379f9d2.js:800:52
    at Array.sort (<anonymous>)
    at TransformationPanel._collectMovableObjects (panel-transformation.9379f9d2.js:800:22)
    at TransformationPanel.moveObjects (panel-transformation.9379f9d2.js:809:33)
```

It might be that these issues are related, why I combine it into one issue for now.

**Comment by justvanrossum** [comment]
Ouch, good catch!
