### ISSUE TITLE
Bug: copy .fontra file and overwrite same path

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1858]
Based on user feedback within the discord channel #questions.

I can reproduce the issue with the latest Fontra Pak. 

I also can reproduce the issue with fontra, via terminal:
`fontra-copy '/Users/ollimeier/Documents/hithub_data/fontra/test-common/fonts/MutatorSans.fontra' '/Users/ollimeier/Documents/hithub_data/fontra/test-common/fonts/MutatorSans.fontra'`

The following error occurs:
```
(fontra) ollimeier@Ollis-MacBook-Pro fontra % fontra-copy '/Users/ollimeier/Documents/hithub_data/fontra/test-common/fonts/MutatorSans.fontra' '/Users/ollimeier/Documents/hithub_data/fontra/test-common/fonts/MutatorSans.fontra'        
Traceback (most recent call last):
  File "/Users/ollimeier/Documents/hithub_data/fontra/venv/bin/fontra-copy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ollimeier/Documents/hithub_data/fontra/src/fontra/backends/copy.py", line 222, in main
    asyncio.run(mainAsync())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ollimeier/Documents/hithub_data/fontra/src/fontra/backends/copy.py", line 200, in mainAsync
    sourceBackend = getFileSystemBackend(sourcePath)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ollimeier/Documents/hithub_data/fontra/src/fontra/backends/__init__.py", line 16, in getFileSystemBackend
    return _getFileSystemBackend(path, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ollimeier/Documents/hithub_data/fontra/src/fontra/backends/__init__.py", line 29, in _getFileSystemBackend
    raise FileNotFoundError(path)
FileNotFoundError: /Users/ollimeier/Documents/hithub_data/fontra/test-common/fonts/MutatorSans.fontra
```

**Comment by justvanrossum** [comment]
Fixed by #1860.
